kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bookinfo
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: "system:serviceaccounts:{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: bookinfo-scc-usage
