{{- $namespace := cat $.Values.global.pattern $.Values.clusterGroup.name | replace " " "-" }}
{{ if .Values.clusterGroup.isHubCluster }}
{{- range .Values.clusterGroup.externalClusters }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: {{ . | kebabcase }}-secret
  namespace: {{ $namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ . | kebabcase }}-secret
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
  dataFrom:
  - extract:
      key: {{ $.Values.secretsBase.key }}/cluster_{{ . }}
{{- end }}
{{ end }}