{{ if .Values.clusterGroup.isHubCluster }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: license-secret
  namespace: kong
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: license-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.secretsBase.key }}/kong
{{ end }}
