apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reviews.name" . }}-v1
  labels:
    {{- include "reviews.labels" . | nindent 4 }}
    version: v1
spec:
  replicas: {{ .Values.replicaCount | default .Values.global.replicaCount }}
  selector:
    matchLabels:
      {{- include "reviews.selectorLabels" . | nindent 6 }}
      version: v1
  template:
    metadata:
      labels:
        {{- include "reviews.selectorLabels" . | nindent 8 }}
        version: v1
    spec:
      serviceAccountName: {{ include "reviews.serviceAccountName" . }}
      containers:
        - name: reviews
          image: "{{ .Values.image.repository }}-v1:{{ .Values.image.tag | default .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default .Values.global.image.pullPolicy }}
          env:
            - name: LOG_DIR
              value: "/tmp/logs"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: wlp-output
              mountPath: /opt/ibm/wlp/output
          securityContext:
            runAsUser: 1000
      volumes:
        - name: wlp-output
          emptyDir: {}
        - name: tmp
          emptyDir: {}
